framework:
    messenger:
        transports:
            sms_async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: sms
            mail_async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: mail

        routing:
            App\Message\SmsNotification: sms_async
            Symfony\Component\Mailer\Messenger\SendEmailMessage: mail_async