security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: ROLE_TRAINER
        ROLE_TRAINER: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    providers:
        user_email_provider:
            entity:
                class: App\Entity\User
                property: email
        user_token_provider:
            entity:
                class: App\Entity\User
                property: apiToken
        all_users:
            chain:
                providers: ['user_email_provider','user_token_provider']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            lazy: true
            pattern: ^/admin
            provider: all_users
            form_login:
                login_path: admin_login
                check_path: admin_login
            logout:
                path: app_logout
                target: admin_login
        api:
            lazy: true
            provider: all_users
            stateless: true
            json_login:
                check_path: api_login
            guard:
             authenticators:
                - App\Security\TokenAuthenticator
        main:
            lazy: true
            provider: all_users
            stateless: true
            http_basic:
                realm: Secured Area

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: PUBLIC_ACCESS, methods:[POST] }
        - { path: ^/api/users, roles: PUBLIC_ACCESS, methods:[POST, PATCH] }
        - { path: ^/users/, roles: PUBLIC_ACCESS, methods:[POST] }
        - { path: ^/api/programmes, roles: ROLE_ADMIN }
        - { path: ^api/programmes, roles: ROLE_USER, methods:[POST] }
        - { path: ^/api/users, roles: ROLE_ADMIN }
        - { path: ^/api/newsletter, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN] }

when@test:
    security:
        password_hashers:

            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
