parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $programmeMinTimeInMinutes: '%env(PROGRAMME_MIN_TIME_IN_MINUTES)%'
            $programmeMaxTimeInMinutes: '%env(PROGRAMME_MAX_TIME_IN_MINUTES)%'
            $maxPerPage: '%env(MAX_PER_PAGE)%'
            $version: '%env(VERSION)%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    App\EventListener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
