parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $programmeMinTimeInMinutes: '%env(PROGRAMME_MIN_TIME_IN_MINUTES)%'
            $programmeMaxTimeInMinutes: '%env(PROGRAMME_MAX_TIME_IN_MINUTES)%'
            $maxPerPage: '%env(MAX_PER_PAGE)%'
            $apiVersion: '%env(API_VERSION)%'
            $handlerToImportFrom: '%env(HANDLER_IMPORT_FROM)%'
            $handlerToImportMistakes: '%env(HANDLER_IMPORT_MISTAKES)%'
            $analyticsLog: '%env(ANALYTICS_LOG_FILE)%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

#    App\EventSubscriber\ApiLoginSubscriber:
#        tags:
#            - name: kernel.event_subscriber
#              dispatcher: security.event_dispatcher.api