# This is a basic workflow to help you get started with Actions

name: FirstAction

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: action-php-codesniffer
        # You may pin to the exact commit or the version.
        # uses: tinovyatkin/action-php-codesniffer@0043b33b3629611c37e8bc7ee8a4e061dc9a7ea2
        uses: tinovyatkin/action-php-codesniffer@v1
        
      - name: PHP Code Style Fixer (php-cs-fixer)
        # You may pin to the exact commit or the version.
        # uses: StephaneBour/actions-php-cs-fixer@7859a1c7cf1fa71397960e2fe1c86bcbccfec21e
        uses: StephaneBour/actions-php-cs-fixer@7.4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
